global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:5000']

  - job_name: 'users_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['users_service:5001']

  - job_name: 'products_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['products_service:5002']