name: Users Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/users_service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'microservices/users_service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r microservices/users_service/requirements.txt

      - name: Build Docker image
        run: docker build -t users-service-image ./microservices/users_service

      - name: Run tests
        run: |
          cd microservices/users_service
          pytest tests/
        env:
          DATABASE_URL: sqlite:///:memory:

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image
      #   run: docker push your_dockerhub_username/users-service-image:latest
